server:
   port: 9001

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:
          - path:/users/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     deafultZone: http://localhost:8761/eureka   
           