server:
  port: 9004
spring:
  application:
    name: RatingService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/ratinginfo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
eureka:
 instance:
    prefer-ip-address: true
 client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     deafultZone: http://localhost:8761/eureka 
 
       
      
      
      

